
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sz_1904?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    password: 123
    username: root
    driver: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
mybatis:
  mapper-locations: classpath:/mapper/*.xml